services:
  app:
    build: 
      dockerfile: ./php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: app
    volumes:
      - ./src:/src

  db:
    container_name: db
    image: mysql:9.0
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    env_file: .env

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "9000:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
